# POST http://localhost:9000/user/register HTTP/1.1
# content-type: application/json

# {
#   "id": "test2",
#   "name": "테스트2",
#   "nickname": "글작성개발중",
#   "email": "test2@example.com",
#   "role": 1,
#   "password": "qwer"
# }

GET http://localhost:9000/post?offset=d HTTP/1.1
# GET http://localhost:9000/post/2dcd05d0-37db-11ed-b4d1-1b0fde2043ce HTTP/1.1

# PUT http://localhost:9000/post HTTP/1.1
# content-type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidGVzdDIiLCJpYXQiOjE2NjM1NjgyMTcsImV4cCI6MTY2MzY1NDYxN30.53wM0CQk7Z3D3epih2pzBppzFrWUfZc_8VukLk9DQtg

# {
#   "id": "46fdc650-37dd-11ed-9a5c-1382d6dfde0d",
#   "title": "글 제목22",
#   "content": "내용22"
# }

# DELETE http://localhost:9000/post?id=46fdc650-37dd-11ed-9a5c-1382d6dfde0d HTTP/1.1
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidGVzdDIiLCJpYXQiOjE2NjM1NjgyMTcsImV4cCI6MTY2MzY1NDYxN30.53wM0CQk7Z3D3epih2pzBppzFrWUfZc_8VukLk9DQtg

# POST http://localhost:9000/user/login HTTP/1.1
# content-type: application/json

# {
#   "id": "test1",
#   "password": "qwer"
# }

# 없는 API
# DELETE http://localhost:9000/list HTTP/1.1
